#Object Definitions
==================================================================================== 
getlbl_TutoredActivity                         xpath                           //div[contains(@class,'week-current')]//div[contains(@data-activity-name,'${description}')]
titleOfActivity                                xpath                           //div[@id='appFrames']//div[contains(@style,'block')]//*[@class[contains(.,'nb_actTitle nb_math')]]
link_submitForTutored                          xpath                           //li[contains(text(),'Submit for Grading')]
CloseActivityButton                            xpath                           //div[@id='appFrames']//div[contains(@style,'block')]//a[@class='closeActivity']
IntoQuickPrep                                  xpath                           (//span[contains(text(),'Introduction and Quick Prep')])[1]
getFrame_Content                               xpath                           //*[contains(@id,'_NB_Main_IFrame') and contains(@title,'Assessments App')]
getFrame_StudyCenter                           xpath                           //*[contains(@id,'_NB_Main_IFrame') and contains(@title,'Study Center App')]
checkOverviewStatus                            xpath                           //*[text()='Preparation']
link_submitForIntro                            id                              submit
lbl_Mastery                                    xpath                           (//span[contains(text(),'Mastery')])[1]
lbl_Review                                     xpath                           (//span[contains(text(),'Review')])[1]
lbl_Challenge                                  xpath                           (//span[contains(text(),'Challenge')])[1]
lbl_StudyGuide                                 xpath                           (//span[contains(text(),'Study Guide')])[1]
gettxt_KeyConcepts                             xpath                           //*[@class='title' and contains(text(), 'Key Concepts')]
CloseStudyGuide                                xpath                           //span[contains(@class,'glyphicon-remove-circle')]
startActivityForTutored                        xpath                           //*[contains(text(),'Start Activity')]
submitForTutored                               id                              nav-group-submit
SubmitActivity                                 xpath                           //div[text()='Submit Activity for Grading']
SubmitConfirm                                  xpath                           //button[@id='warning-submit']
img_DoneActivity                               xpath                           //img[@alt='Done']
checkOverviewStatus                            xpath                           //*[text()='Overview']/parent::div[@class='sel-item']
get_StateForSubmit                             xpath                           //div[@class='nav-groups']//div[contains(@class,'group selected')]
getbtn_Next                                    xpath                           //div[text()='Next']
ActivitySubmitted                              xpath                           //div[text()='SUBMITTED!']
SubmitMastery                                  xpath                           //button[contains(@class, 'submit-final')]
MasteryGroup                                   xpath                           (//div[contains(@class, 'text')])[1]
activityLaunch_Link                            xpath                           //div[@class='assignmentName' and @data-activity-name = '${value}']
activityOverview_Header                        xpath                           //b[text()='${value}']
cancel_btn                                     xpath                           //button[text()='Cancel']
gradeLabel                                     xpath                           //p[contains(text(), 'This is a graded activity worth')]
attemptLabel                                   xpath                           //p[contains(text(),'You can attempt each question set up to')]
connectionLost_Label                           xpath                           //p[contains(text(),'If you lose connection during your attempt, you will be able to resume the assignment within a few minutes')]
startActivity_btn                              xpath                           //button[text()='Start Activity']
activityInfo_icon                              xpath                           //span[text()='Activity Overview']
activityReading_btn                            xpath                           //span[text()='Reading']
activityTitle                                  xpath                           //div[text()='${value}']
activityScore                                  xpath                           //li[contains(text(),'points')]
activityDate                                   xpath                           //div[@class='nb_actStatus']
submittedDecorator                             xpath                           (//img[contains(@src,'/static/nb/ui/images/prog_done_sm.png')])[3]
review_btn                                     xpath                           //input[@value='Review']
submitted_btn                                  xpath                           //button[(contains(text(),'Submitted'))]
close_activity                                 xpath                           //a[@id='app_activity_frame_closeActivity']
activity_overview_btn                          xpath                           //span[text()='Activity Information']
collapse_link                                  xpath                           //button[contains(text(),'Collapse')]
expandLink                                     xpath                           (//div[@class='accordion-collapsed-mask'])[1]
InProg_SI                                      xpath                            //span[text()='${value}']/../../..//i[@class='statusIcon inprogress']
check_answer_btn                               xpath                            //button[contains(text(),'Check Answer')]
dis_board_post_new_message_btn                 xpath                            //button[contains(text(),'Post new message')]
close_and_submit_btn                           xpath                            //button[contains(text(),'Close and Submit')]
key_concept                                    xpath                            //h2[@class='title' and contains(text(),'Key Concepts')]
key_equation                                   xpath                           //h2[@class='title' and contains(text(),'Key Equations')]
key_terms                                      xpath                           //h2[@class='title' and contains(text(),'Key Terms')]
cross_icon_display                             xpath                           //span[@class='glyphicon glyphicon-remove-circle']
print_icon_display                             xpath                           //h4[@class='pull-right']//span[@class='glyphicon glyphicon-print'  ]
activity_number                                xpath                           //h4[@class='heading-section ng-binding']
StudycenterFrame                               xpath                           //iframe[@id='119_NB_Main_IFrame']
behindstudyguide                               xpath                           //div[@class='nb_actTitle nb_math']
countOfStudyGuide                              xpath                           //div[contains(@title, 'Study Guide')]//span[contains(@class, 'lpn_dm_name')]
unitStudyGuide                                 xpath                           (//div[contains(@title, 'Study Guide')]//span[contains(@class, 'lpn_dm_name')])[${description}]
clickStudyGuide                                xpath                            //span[@id='lpn_dm_name_20071246']
======================================================================================================================================================


