#Object Definitions
================================================================================================================================= 
CreateStudy                        xpath                       //button[@class='btn btn-info btn-studyguide']
GuideTitle                         id                          studyGuideName
dropDown                           class                       content-select
SelectAllCheckbox                  xpath                       //input[@type='checkbox' and @ng-click='toggleAll()']
AddUnit                            xpath                       //button[@class='btn btn-sm btn-info btn-syncUnit']
CreateGuide                        xpath                       //button[@type='submit']
StudyTitle                         xpath                       //div[@class='title ng-binding']
StudyLaunch                        xpath                       (//div[@class='study-guide']/div[text()='${value}'])[1]
LaunchTitle                        xpath                       //h2[@class='ng-binding']
refreshIcon                        xpath                       //a[@class='refresh']
PrintIcon                          xpath                       //a[@tooltip='Print']
HideIcon                           xpath                       //a[@tooltip='Hide']
DeleteIcon                         xpath                       //a[@class='delete']   
SortText                           xpath                       //ul[@class='sort']/li[1]
TypeSort                           xpath                       //ul[@class='sort']/li[2]
UnitSort                           xpath                       //ul[@class='sort']/li[3]    
DeleteOkButton                     xpath                       //button[@ng-click='ok()']   
HighlightHeading                   xpath                       (.//*[@id='highlights']/div/h3)[2]
KeyHeading                         xpath                       (.//*[@id='key-terms'])[1]        
NotesHeading                       xpath                        (.//h3[@class='title ng-binding'])[5]
FlashHeading                       xpath                       (.//h3[@class='title ng-binding'])[6]
HighlightContent                    xpath                       (//div[@class='alert alert-info ng-scope'])[1]
NotesContent                       xpath                       (//div[@class='alert alert-info ng-scope'])[2]
FlashContent                       xpath                       (//div[@class='alert alert-info ng-scope'])[3]
BackLink                           xpath                       //a[@class='navigation-back']
SelectedUnit_Title                 xpath                       //option[@value='8']
DelIcon                            xpath                         (//div[text()='${val}']/..//a[@class='delete'])[1]
DelOK                              xpath                        //button[@ng-click='ok()']
BookMarkIcon                       xpath                       //a[@class='bookmarks']
StudyGuideIcon                     xpath                       //a[@class='study-guides']
HighlightsIcon                     xpath                       //a[@class='annotations']
HideIcon                           xpath                       //div[text()='${val}']/..//a[@class='view remove']
BookmarkCount                      xpath                       .//*[@id='bookmarks-container']/div[1]/h2/ng-pluralize
NoBookmarkMessage                  xpath                        //h4[text()='There are no bookmarks to display.']
AddBookmarkMessage                 xpath                        //p[text()='Add bookmarks by clicking on the bookmark icon at the top of the Reader.']
CloseApp                           xpath                        //a[@title='Close App']
Activity_BookmarkLink              xpath                        //a[span[text()='Add Bookmark to this Page']]
ClickedBookmarkLink                xpath                        //span[text()="Remove this page's Bookmark"]
unitName_link                      xpath                        //a[contains(.,'${unitName}')]
BookmarkDelOKIcon                 xpath                        //button[@ng-click='ok()']   
highlighttext                       xpath                       //p[@id='XQQAWY876654190']                 

================================================================================================================================= 