#Object Definitions
====================================================================================
gradeBookApp                               xpath                   //h2[@class='nb_panelName' and contains(.,'Progress')]
dropdown_overallPerformanceSelector        xpath                   //select[@ng-model='model.finalScoreFilter']
overallpercent                             xpath                   //span[@class='overallPercent']
btn_expandgradebook                         xpath                   //a[contains(.,'Expand All Grades')]
btn_collapsedgradebook                      xpath                   //a[contains(.,'Collapse All Grades')]
gradescellsingrid                           xpath                   //div[contains(@class,'ag-body-container')]//div[contains(@class,'ag-cell-value')]
totalPossiblePoints                         xpath                   //div[contains(@class,'ngHeaderText')]/following-sibling::div[@class='student-roster-points-possible']
gradedActivitiesTitlesInGrid                xpath                   //div[contains(@class,'ag-header-group-cell-with-group')]/following-sibling::div[contains(@class,'ag-header-cell')]//span[@class='ngHeaderTitle']
manualgradeactivity                         xpath                      //span[contains(@class,'activity manualGrade')]/../span[2]
link_student                               xpath                   //div[@data-e2e-class='StudentName' and contains(., '${studentname}')]
btn_scorebreakdown                         xpath                       //button[@data-e2e-id='ScoreBreakdownButton']
txt_pendinggradingbyinstructor             xpath                       //span[@data-e2e-class='PendingManualGradingMessage']
manualgradeactivitywithoutgrades           xpath                       //span[@class='activity manualGrade']//../../../..//div[contains(@class,'score') and not (contains(text(),'%'))]/..//div[contains(@class,'submitted') and not (contains(text(),'--'))]/../div//span[contains(@title,.) and not (contains(@class,.))]
activty                                    xpath                       //*[@id='center']/div/div[4]/div[2]/div/div/div[3]/div[1]/span/span/span[2]
btn_closemodal                             xpath                           //button[@data-e2e-id='ModalCloseButton']
categoryinputbox                           xpath                           //input[contains(@class,'ui-select-search')]                         
categoryselectchoice                       xpath                           //a[@class='ui-select-choices-row-inner']
applyfilterbutton                          xpath                           //button[contains(@class,'apply-filter')]
link_filterassignments                     xpath                       //a[@class='filter-gradebook']
activitywithoutscore                       xpath                       (//span[@class='activity']/../span[2])[1]
btn_editscore                              xpath                           //button[contains(.,'Edit Score')]
txt_editscorebox                           xpath                           (//div[contains(@class,'score')]/input[@type='number'])[1]
btn_savescrore                             xpath                            //button[contains(.,'Save') and contains(@ng-click,'saveScore')]
pointscored                                 xpath                           //strong[contains(@ng-bind-html,'getPointsScoreToString')]
commentduetochangedate                      xpath                           (//ul[contains(@class,'comments')]/li)[1]
btn_modalclose                                   xpath                               //button[@data-e2e-id='ModalCloseButton']
link_activity                              xpath                   (//span[contains(@title,'${activityname}')])[1]
activitytext                               xpath                    //div[@class='activity-name ng-binding' and contains(.,'${activityname}')]
dropdown_performance                       xpath                    //select[@data-e2e-id='OverallPerformanceDropDown']
btn_expandAllGrades                        xpath                    //a[@data-e2e-id='ExpandCollapseLink']
tab_student                                xpath                     //div[@data-e2e-class='StudentName']
btn_close                                  xpath                     //button[@class='close'][@title='Close']
performance                                xpath                     //select[@data-e2e-id='OverallPerformanceDropDown' and Contains(.,'${option}')]
fetchactivitybyname                         xpath                       //span[@class='activity']/../span[contains(@title,'${activitytitle}')]
learningpath                                xpath                           //span[@class='ag-header-cell-text'][contains(text(),'Learning Path')]
btn_back                                    xpath                           //a[@class='backButton']
link_closeapp                             xpath                           //a[@title='Close App']
button_dateselector                         xpath                               //button[contains(@class,'dateselect')]
link_date                                   xpath                                   //td[@class='text-center ng-scope']/button
btn_duedateselector                        xpath                             //button[contains(@class,'dateselect')]
showextendedduedate                         xpath                           html/body/div[3]/div[2]/ng-include/div/div[4]/ul/li[1]
btn_done                                    xpath                               //button[contains(.,'Done')]
commentnoteditable                          xpath                                   (//strong[contains(@class,'ng-binding')])[8]
hide_gradebook                              xpath                                   //div[contains(@style,'block')]//a[contains(@class,'hideApp')]
tab_overview                                xpath                                   //div[contains(text(),'Overview')]
bar_activityheader                          xpath                                   //div[@class='ag-header-viewport']
verificationid                              xpath                                   //div[contains(@class,'ag-cell-value') and contains(.,'student')]
scoreDispBox                                xpath                                   //div[@class='count_box' and contains(.,'AVERAGE SCORE')]
btn_displaysettings                         xpath                                       //a[contains(.,'Display Settings')]
btn_savedisplaysetting                      xpath                                       //button[@data-e2e-id='SaveDisplaySettingsButton']
btn_points                                  xpath               `                           //div[contains(@class,'radio') and contains(.,'Points')]//input
scoreinpoint                                xpath                                  //div[text()=' user2, auto']/../..//span[@class='overallPoints']
collapsedcategory                            xpath                                       //span[@class='category-icon']
pointsavailable                 xpath               //div[text()='Points Available So Far']
expandGradeBook_btn             xpath               //a[contains(.,'Expand All Grades')]
collapsedGradeBook_btn          xpath               //a[contains(.,'Collapse All Grades')]
gradesCellsInGrid               xpath               //div[contains(@class,'ag-body-container')]//div[contains(@class,'ag-cell-value')]
closeBtn                        xpath               //button[@class='close']
toggle_switch                   xpath               //span[@class='toggleSwitchButton toggleSpeedGrade ng-valid toggle-off']
showDetailsLink                 xpath               //span[@class='icon icon-expand']
hideDetailsLink                 xpath               //span[@class='icon icon-collapse']
ProgressApp                    xpath         //*[@id='app_viewProgress']/img
ExpandAllGrades_btn            xpath         //a[@data-e2e-id='ExpandCollapseLink']
ActivityTitle                  xpath         //div[@class='header-cell-2']//span
Overview_tab                   xpath         //a[contains(.,'Overview')]
Analytics_tab                  xpath         //a[@class='topTab topTab_selected']
GradeBook_tab                  xpath         //a[contains(.,'Gradebook')]
Categorize_tab                 xpath         //span[contains(@class,'progress_category')]
HelpOverlay_btn                xpath         //span[@data-e2e-id='HelpIcon']
CloseOverlay_btn               xpath         //a[@class='close']
EngagementLevel_btn            xpath         //img[@class='gwt-Image']
SelectStudent                  xpath         //div[contains(text(),'${studentname}')]
Score_Breakdown_btn            xpath         //button[@data-e2e-id='ScoreBreakdownButton']
Drop_Student_btn               xpath         //button[@data-e2e-id='DropStudentButton']
student_email_link             xpath         //a[@class='btn-link ng-binding']
select_activity                xpath         //span[contains(text(),'${activityname}')]
grade_activity_btn_enabled      xpath       //button[contains(.,'Grade Activity') and @ng-disabled='!buttonIsEnabled']
grade_activity_btn_disabled     xpath       //button[contains(.,'Grade Activity') and @disabled='disabled']
manualgradeactivity_noattmpt    xpath       (//span[@class='activity manualGrade']//../../../..//div[contains(@class,'submitted') and (contains(text(),'--'))]/..//span[contains(@class,'manual')])[1]
manualgradeactivity_attmpt      xpath       (//span[@class='activity manualGrade']//../../../..//div[contains(@class,'submitted') and (contains(text(),'1'))]/..//span[contains(@class,'manual')])[1]
gradedactivity_attmpt           xpath       (//span[@class='activity']//../../../..//div[contains(@class,'submitted') and (contains(text(),'1'))]/..//span[contains(@class,'activity')])[1]
gradedactivity_noattmpt         xpath       (//span[@class='activity']//../../../..//div[contains(@class,'submitted') and (contains(text(),'--'))]/..//span[contains(@class,'activity')])[1]
submission_msg                  xpath       //span[text()='0 submissions to grade']
editscore_btn                   xpath       //button[text()='Edit Score']
recorded_score                  xpath       //strong[contains(@ng-bind-html,'Percentage')]
input_score                     xpath       //input[@data-e2e-id='PointsInput']
save_btn                        xpath       //button[@class='btn btn-success']
view_btn                        xpath       //button[@ng-click='openAttempt()']
submitted_msg                   xpath       //div[text()='The score from the last attempt is recorded']
submitted_best_msg              xpath       //div[text()='The best score from all attempts is recorded']
comments                        xpath       //li[@class='ng-scope']
removescore_btn                 xpath       //button[@ng-click='confirmScoreDeletion()']
confirm_btn                     xpath       //button[text()='Confirm']
student_score                   xpath       //div[contains(text(),'qad, student')]/../..//span[@class='overallPercent']
back_btn                        xpath       //a[@class='backButton']
total_list                      xpath       //span[contains(@class,'activity')]
student_score                   css         svg.class_average
activitiesscore                 xpath       //div[contains(@class,'ag-cell ag-cell-no-focus cell-col-') and contains(@style,' absolute; left') ]//div
expandicon                      xpath           //span[contains(@class,'ag-header-expand-icon')]
category_icon                   xpath               //span[@class='category-icon']
====================================================================================