#Object Definitions
================================================================================================================================= 
outlineBuilderIcon                          xpath                       //a[@title='Outline Builder']
outlineBuilder_icon                         xpath                       //img[contains(@src,'dockItem')]
categoryHeader                              xpath                       //span[@class='appActionFrame_actionLabel']
more_link                                   xpath                       //a[@title='Expand Dock']
save_btn                                    xpath                       //input[@value='Save']
error_message                               xpath                       //span[@class='instructor-activity-error-message ng-binding']
cancel_btn                                  xpath                       //button[text()='Cancel']
ok_btn                                      xpath                       //button[text()='OK']
createasgnmnt_btn                           xpath                       //button[text()='Create Assignment']
asgnmnt_name                                xpath                       //input[@name='assignmentName']
asgnmnt_desc                                xpath                       //textarea[@name='description']
viewmod_ques                                xpath                       (//a[@class='ng-binding'])[position()=1]
addques_link                                xpath                       //a[text()='Add Question']
mulchoice_link                              xpath                       //a[text()='Multiple Choice']
mulselect_link                              xpath                       //a[text()='Multiple Select']
ques_text                                   xpath                       .//*[@id='taTextElement']
answer_text                                 xpath                       //input[@ng-model='opt.text']
answer_save_btn                             xpath                       //button[text()='Save']
citation_field                              xpath                       //select[@name='citationTypeSelect']
practice_checkbox                           xpath                       //input[@type='checkbox']
graded_activity                             xpath                       //div[text()='${desc}']/../../..//a[@class='ng-binding']
preview_ques                                xpath                       //div[@class='ng-pristine ng-valid']
close_btn                                   xpath                       //input[@value='Close']
graded_activity_edit_icon                   xpath                       //div[text()='${name}']/../../..//img[@title='Edit']
points_input                                xpath                       //input[@name='pts']
radio_btn                                   xpath                       //div[text()='${desc}']/../../..//input[@type='radio']
continue_btn                                xpath                       //button[@id='ContinueButton']
available_input                             xpath                       .//*[@id='startDate']
due_input                                   xpath                       .//*[@id='endDate']
done_btn                                    xpath                       //button[text()='Done']
next_btn                                    xpath                       //span[text()='Next']
due_date                                    xpath                       //a[text()='10']
selectMenu_Order                            xpath                       //div[@class='order_select']//span[contains(@class,'ui-selectmenu-status')]
save_btn                                    xpath                       //a[@class='adminButton save']
selectPosition                              xpath                       //ul[@id='order-menu']//li['${position}'] 
editoptions_btn                             xpath                       //input[@value='Edit Options']
================================================================================================================================= 