
#Object Definitions
========================================================================================================
lbl_appName                          xpath          //div[contains(@class,'dockGroup')]/li/a/img
dockGroup1                           xpath          //div[@id='dockGroup1']/li
appNameLink                          xpath          //div[contains(@class,'dockGroup')]/li/a
HeadingNameOfTheApp                  xpath          //div[contains(@id,'NB_App_DockItem') and contains(@style,'display: block')]//h2/span[text()="${appName}"]
getCollapse                          xpath          //div[contains(@id,'NB_App_DockItem') and contains(@style,'display: block')]//a[contains(@class,'hideApp')]
getCollapse                          xpath          //div[contains(@id,'NB_App_DockItem') and contains(@style,'display: block')]//a[contains(@class,'hideApp')]
FullGradebook                        id             allScores
getTab_Week                          xpath          //*[@panes='tabs']//li[contains(@title,'Week View')]
getTab_DateManager                   xpath          //*[@panes='tabs']//li[contains(@title, 'Date Manager')]
getTab_ListView                      xpath          //*[@panes='tabs']//li[contains(@title, 'List View')]
getTab_Unit                          xpath          //*[@panes='tabs']//li[contains(@title, 'Unit View')]
LPNUnitImg                           xpath          (//*[@id='lpn_list_area']//div[@class='thumbBar']/img[contains(@src,'unit')])[1]
Search_TxtBox                        xpath           //input[contains(@class, 'search') and contains(@type, 'text')]
StudyCenter_txt                      xpath           //h3[contains(text(), 'QuizMe')]
RssFeed_txt                          xpath           //span[contains(text(), 'Available Feeds')]
chemistryReference_txt               xpath           //a[contains(text(), 'Elements')]
Flashcard_txt                        xpath           //span[contains(@class, 'ui-selectmenu-status')]
FullBook_txt                         xpath           //a[contains(text(), 'Chapters')]
Glossary_txt                         xpath           //span[contains(text(), 'Glossary Terms')]
Gradebook_txt                        xpath           //div[contains(text(), 'Gradebook')]
studentGradebook                     id              studentName
Dictionary_txt                       xpath           //p[contains(text(), 'Merriam-Webster')]
Unit_Back                            xpath           //span[contains(@style,'display: block')]/a[contains(text(), 'back') and contains(@class, 'navLink')]
lpn_title                            xpath           (//span[@class='lpn_title ng-binding'])[1]
current_week                         xpath           .//*[contains(@class,'week-current')]
performance_widget_title             xpath            //*[@id='perfTitleText']
class_average                        xpath            //*[@id='perfClassAverageScore']
your_current_score_txt               xpath            .//div[contains(@id,'perfCurrentScoreText')]
course_settings_link                 xpath            //a[contains(text(),'Course Settings')]
user_menu_link                       xpath            //div[@id='nb_menu_overlay']//a[@class='user-menu-link tb_item']
customer_support_link                xpath            //a[contains(text(),'Customer Support')]
get_started_tut_link                 xpath            //a[contains(text(),'Getting Started Tutorial')]
send_us_feedback_link                xpath            //a[contains(text(),'Send Us Feedback')]
faq_link                             xpath            //a[contains(text(),'FAQ')]
system_check_link                    xpath            //a[contains(text(),'System Check')]
logout_link                          xpath            //a[contains(text(),'Logout')]
mindtap_logo_img                     xpath            .//div[@class='logoMT']/img[@alt="MindTap Logo"]
aboutCengageLink                     xpath            .//a[text()='About Cengage Learning']
AboutUs                              xpath            .//*[@id='splash_contentdiv']/h3[contains(text(),'About Us')]
copyrightStatmentLink                xpath            .//a[text()='Copyright Statement']
copyrightInfo                        xpath            .//*[@id='header']/h1[contains(text(),'Copyright')]
serviceAgreementLink                 xpath            .//a[contains(text(),'Service Agreement')]
serviceAgreementInfo                 xpath            .//*[@id='splash_contentdiv']/h3[contains(text(),'SERVICE AGREEMENT')]
splash_close_btn                     xpath            .//a[contains(@class,'splash_close nb_closeIcon')]
lpn_unit_link                        xpath             //h3[@class='lpn_name']//a[contains(text(),'Unit 4')]
lpn_title_inside_unit                xpath             .//*[@id='lpn_toolbar']//span[@class="lpn_title"]
con_with_politics_lpn_link           xpath             //h3[@class='lpn_name']//a[contains(text(),'Connecting with Politics')]
con_narrative_lpn_link               xpath             //h3[@class='lpn_name']//a[contains(text(),'Pursuing Equality')]
disc_board_lpn_link                  xpath             //h3[@class='lpn_name']//a[contains(text(),'In the Know')]
contextual_lens_lpn_link             xpath             //h3[@class='lpn_name']//a[contains(text(),'4.8 Why Politics Matters: Youth and Politics')]
essay_act_lpn_link                   xpath             //h3[@class='lpn_name']//a[contains(text(),'4.9 Why Politics Matters: Then and Now Essay')]
study_guide_lpn_link                 xpath             //h3[@class='lpn_name']//a[contains(text(),'Study Guide')]
msg_center_submit_btn                xpath             .//*[@id='message_submit']
polling_inside_text                  xpath             .//*[@id='instructor-wrap']//h2[contains(text(),'Student Polls for this Course')]
mer_webster_inside_txt               xpath             .//*[@id='mtdict-content']/p[contains(text(),"Merriam-Webster's Dictionary")]
msg_center_stu_refresh_link          xpath             //a[contains(@class,'view_message_refresh')]
polling_stu_refresh_link             xpath             //a[contains(.,'refresh your page')]
view_tab                             xpath              //li[@title='${_view_Tab}']
addContent_btn                       xpath           //span[@class='lpn_create']
addActivity_link                     xpath           //*[@class='lpn_create active']//*[@class='menu_item activity']/a    
addedActivity_text                   xpath           //h1[text()='Add Activity'] 
activityName_link                    xpath           //h3[contains(text(),'${activityName}')]
cntinu_btn                           xpath           //input[@class='continue_button']
view_tab                             xpath              //li[@title='${_view_Tab}']
add_title                            xpath           //input[@id='name']
add_Discription                      xpath           //textarea[@id='description']
selectMenu_Order                     xpath           //div[@class='order_select']//span[contains(@class,'ui-selectmenu-status')]
selectPosition                       xpath           //ul[@id='order-menu']//li['${position}'] 
saveActivity_btn                     xpath           //span[@id='init_save']
startDate                            xpath         .//*[@id='startDate']
dueDate                              xpath         .//*[@id='endDate']
setDone                              css           button[class*='date-clear date-close']
checkAct                             xpath         (//span[contains(.,'Distinct Web Link Activity')])[1]
currentDate                          xpath          //a[@class='ui-state-default ui-state-highlight ui-state-active' and @href='#']
dueDate_Done_btn                     xpath          //button[text()='Done']
Next                                 xpath           //span[text()='Next']
activityTitle_link                   xpath           (//h3[@class='lpn_name']/a[contains(.,'${activity_title}')])[1]
lpnActivity_link                     xpath           //h3[contains(@class,'lpn_name') and contains(.,'${activity_title}')]/parent::*/parent::*/parent::*
activityDelete_icon                  xpath           //h3[contains(@class,'lpn_name') and contains(.,'${activity_title}')]/parent::*/parent::*/parent::*//a[@title='Delete']
performanceDot                       xpath             //div[contains(@id, 'perfPopup')]//strong[contains(text(), '${description}']
assessmentTitle                      xpath             (//div[contains(@class, 'distinct_Assessment')])[1]

============================================================================================================================================================


